# Generated by Django 4.0.3 on 2022-03-26 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=20)),
                ('asigne_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_plant', models.CharField(max_length=30)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.company')),
            ],
        ),
        migrations.CreateModel(
            name='TypeMedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medition_name', models.CharField(max_length=35)),
                ('unity_type', models.CharField(max_length=5)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turns', models.CharField(choices=[('M', 'matutino'), ('E', 'evening'), ('N', 'night')], max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name', models.CharField(max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.plant')),
                ('type_medition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.typemedition')),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField(max_length=3)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitoring.sensor')),
            ],
        ),
    ]
